/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FIcons {
        "color": string;
        "group": string;
        "name": string;
        "size": string;
    }
}
declare global {
    interface HTMLFIconsElement extends Components.FIcons, HTMLStencilElement {
    }
    var HTMLFIconsElement: {
        prototype: HTMLFIconsElement;
        new (): HTMLFIconsElement;
    };
    interface HTMLElementTagNameMap {
        "f-icons": HTMLFIconsElement;
    }
}
declare namespace LocalJSX {
    interface FIcons {
        "color"?: string;
        "group"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface IntrinsicElements {
        "f-icons": FIcons;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "f-icons": LocalJSX.FIcons & JSXBase.HTMLAttributes<HTMLFIconsElement>;
        }
    }
}
